plugins {
    id 'com.android.application'
}

android {
    namespace 'com.punkvid.studio'
    compileSdk 34

    defaultConfig {
        applicationId "com.punkvid.studio"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "2.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
